/**
 * Los íconos en PNG (generados por assets/iconos/generar.mjs desde los trazos de iconos.ts: no se
 * editan a mano). Blancos sobre transparente; el color lo pone `tintColor`.
 */
import type { NombreIcono } from './iconos';

export const IMAGENES_ICONOS: Record<NombreIcono, number> = {
  atras: require('../../assets/iconos/atras.png'),
  adelante: require('../../assets/iconos/adelante.png'),
  cerrar: require('../../assets/iconos/cerrar.png'),
  check: require('../../assets/iconos/check.png'),
  microfono: require('../../assets/iconos/microfono.png'),
  camara: require('../../assets/iconos/camara.png'),
  bluetooth: require('../../assets/iconos/bluetooth.png'),
  campana: require('../../assets/iconos/campana.png'),
  ubicacion: require('../../assets/iconos/ubicacion.png'),
  sol: require('../../assets/iconos/sol.png'),
  luna: require('../../assets/iconos/luna.png'),
  telefono: require('../../assets/iconos/telefono.png'),
  persona: require('../../assets/iconos/persona.png'),
  globo: require('../../assets/iconos/globo.png'),
  candado: require('../../assets/iconos/candado.png'),
  salir: require('../../assets/iconos/salir.png'),
  chat: require('../../assets/iconos/chat.png'),
  llamada: require('../../assets/iconos/llamada.png'),
  corazon: require('../../assets/iconos/corazon.png'),
  chispas: require('../../assets/iconos/chispas.png'),
  info: require('../../assets/iconos/info.png'),
  lapiz: require('../../assets/iconos/lapiz.png'),
  ajustes: require('../../assets/iconos/ajustes.png'),
  pastel: require('../../assets/iconos/pastel.png'),
  musica: require('../../assets/iconos/musica.png'),
  comida: require('../../assets/iconos/comida.png'),
  casa: require('../../assets/iconos/casa.png'),
  trabajo: require('../../assets/iconos/trabajo.png'),
  familia: require('../../assets/iconos/familia.png'),
  escudo: require('../../assets/iconos/escudo.png'),
  huella: require('../../assets/iconos/huella.png'),
  wallet: require('../../assets/iconos/wallet.png'),
  enlace: require('../../assets/iconos/enlace.png'),
  reloj: require('../../assets/iconos/reloj.png'),
  ayuda: require('../../assets/iconos/ayuda.png'),
  volumen: require('../../assets/iconos/volumen.png'),
  oido: require('../../assets/iconos/oido.png'),
  tocar: require('../../assets/iconos/tocar.png'),
  ojo: require('../../assets/iconos/ojo.png'),
  basura: require('../../assets/iconos/basura.png'),
  paleta: require('../../assets/iconos/paleta.png'),
  idioma: require('../../assets/iconos/idioma.png'),
  fiesta: require('../../assets/iconos/fiesta.png'),
  estrella: require('../../assets/iconos/estrella.png'),
  juego: require('../../assets/iconos/juego.png'),
  libro: require('../../assets/iconos/libro.png'),
  iglesia: require('../../assets/iconos/iglesia.png'),
  cara: require('../../assets/iconos/cara.png'),
  flecha: require('../../assets/iconos/flecha.png'),
  mas: require('../../assets/iconos/mas.png'),
  correo: require('../../assets/iconos/correo.png'),
  descargar: require('../../assets/iconos/descargar.png'),
  alerta: require('../../assets/iconos/alerta.png'),
  llave: require('../../assets/iconos/llave.png'),
  ayudaCirculo: require('../../assets/iconos/ayudaCirculo.png'),
};
